#!/usr/bin/env bash

#SBATCH --job-name wingbox-analysis
#SBATCH --cpus-per-task=36
#SBATCH --mem=512G
#SBATCH --time=10:00:00

#SBATCH -o /homes/p292u234/job-reports/%x.%j.out

#SBATCH --mail-user=p292u234@wichita.edu
#SBATCH --mail-type=ALL

export MIN_STRINGER_COUNT=8
export MAX_STRINGER_COUNT=8
export OUTPUT_FILE="out.json"

module load "Python/3.12.3-GCCcore-13.3.0"

source /homes/p292u234/venvs/wingbox/bin/activate

python entry.py

cp ${TMPDIR}/$OUTPUT_FILE /homes/p292u234
