#!/usr/bin/env bash

#SBATCH --job-name wingbox-analysis
#SBATCH --cpus-per-task=36
#SBATCH --mem=512G
#SBATCH --time=10:00:00

#SBATCH -o /homes/p292u234/job-reports/%x.%j.out

#SBATCH --mail-user=p292u234@wichita.edu
#SBATCH --mail-type=ALL

source /homes/p292u234/venvs/wingbox/bin/activate

python entry.py
