#!/usr/bin/env bash

#SBATCH --job-name wingbox-analysis
#SBATCH --cpus-per-task=36
#SBATCH --mem=512G
#SBATCH --mail-user=p292u234@wichita.edu
#SBATCH --mail-type=ALL
#SBATCH --time=1:00

julia entry.jl
